- name: Determine active container
  shell: |
    docker ps --filter "name=jampro-app-blue" --filter "status=running" -q
  register: blue_running
  changed_when: false

- name: Set next color and default port
  set_fact:
    next_color: "{{ 'green' if blue_running.stdout else 'blue' }}"
    default_port: "{{ 8082 if blue_running.stdout else 8081 }}"

- name: Check if default port is in use
  shell: |
    lsof -iTCP:{{ default_port }} -sTCP:LISTEN >/dev/null 2>&1
  register: port_check
  failed_when: false
  changed_when: false

- name: Find an available port if default is taken
  shell: |
    for port in 8083 8084 8085 8086; do
      if ! lsof -iTCP:$port -sTCP:LISTEN >/dev/null 2>&1; then
        echo $port
        break
      fi
    done
  when: port_check.rc == 0
  register: available_port
  changed_when: false

- name: Set next_port fact
  set_fact:
    next_port: "{{ available_port.stdout if port_check.rc == 0 else default_port }}"

- name: Deploy new container
  community.docker.docker_container:
    name: "jampro-app-{{ next_color }}"
    image: "{{ image_name }}"
    state: started
    ports:
      - "{{ next_port }}:80"
    restart_policy: always
    recreate: yes

- name: Update nginx configuration (template)
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    owner: root
    group: root
    mode: '0644'

- name: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded

- name: Remove old container
  community.docker.docker_container:
    name: "jampro-app-{{ 'blue' if next_color == 'green' else 'green' }}"
    state: absent
  ignore_errors: yes
